/* Autogenerated by X16ImageTool */

#ifndef GFX_H
#define GFX_H

#define PALBG1_FILENAME "palbg1.bin"

#define TSBG1_FILENAME "tsbg1.bin"
#define TSBG1_TILE_COUNT 246

#define TMBG1_FILENAME "tmbg1.bin"
#define TMBG1_TILE_WIDTH 40
#define TMBG1_TILE_HEIGHT 30
#define TMBG1_PIXEL_WIDTH 320
#define TMBG1_PIXEL_HEIGHT 240
#define TMBG1_TILE_COUNT 1200

#endif
